import type {
  ContextConfigDefault,
  FastifyBaseLogger,
  FastifySchema,
  FastifyTypeProvider,
  FastifyTypeProviderDefault,
  RawReplyDefaultExpression,
  RawRequestDefaultExpression,
  RawServerBase,
  RawServerDefault,
  RouteGenericInterface,
  RouteHandlerMethod,
  RouteShorthandOptions
} from "fastify";


export interface Route<
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  RawReply extends RawReplyDefaultExpression<RawServer> = RawReplyDefaultExpression<RawServer>,
  TypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  Logger extends FastifyBaseLogger = FastifyBaseLogger,
  RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  ContextConfig = ContextConfigDefault,
  SchemaCompiler extends FastifySchema = FastifySchema
> {
  opts: RouteShorthandOptions<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>;
  handler: RouteHandlerMethod<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>;
}


export interface Routes<
  GetRawServer extends RawServerBase = RawServerDefault,
  GetRawRequest extends RawRequestDefaultExpression<GetRawServer> = RawRequestDefaultExpression<GetRawServer>,
  GetRawReply extends RawReplyDefaultExpression<GetRawServer> = RawReplyDefaultExpression<GetRawServer>,
  GetTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  GetLogger extends FastifyBaseLogger = FastifyBaseLogger,
  GetRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  GetContextConfig = ContextConfigDefault,
  GetSchemaCompiler extends FastifySchema = FastifySchema,
  HeadRawServer extends RawServerBase = RawServerDefault,
  HeadRawRequest extends RawRequestDefaultExpression<HeadRawServer> = RawRequestDefaultExpression<HeadRawServer>,
  HeadRawReply extends RawReplyDefaultExpression<HeadRawServer> = RawReplyDefaultExpression<HeadRawServer>,
  HeadTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  HeadLogger extends FastifyBaseLogger = FastifyBaseLogger,
  HeadRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  HeadContextConfig = ContextConfigDefault,
  HeadSchemaCompiler extends FastifySchema = FastifySchema,
  PostRawServer extends RawServerBase = RawServerDefault,
  PostRawRequest extends RawRequestDefaultExpression<PostRawServer> = RawRequestDefaultExpression<PostRawServer>,
  PostRawReply extends RawReplyDefaultExpression<PostRawServer> = RawReplyDefaultExpression<PostRawServer>,
  PostTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  PostLogger extends FastifyBaseLogger = FastifyBaseLogger,
  PostRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  PostContextConfig = ContextConfigDefault,
  PostSchemaCompiler extends FastifySchema = FastifySchema,
  PutRawServer extends RawServerBase = RawServerDefault,
  PutRawRequest extends RawRequestDefaultExpression<PutRawServer> = RawRequestDefaultExpression<PutRawServer>,
  PutRawReply extends RawReplyDefaultExpression<PutRawServer> = RawReplyDefaultExpression<PutRawServer>,
  PutTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  PutLogger extends FastifyBaseLogger = FastifyBaseLogger,
  PutRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  PutContextConfig = ContextConfigDefault,
  PutSchemaCompiler extends FastifySchema = FastifySchema,
  DeleteRawServer extends RawServerBase = RawServerDefault,
  DeleteRawRequest extends RawRequestDefaultExpression<DeleteRawServer> = RawRequestDefaultExpression<DeleteRawServer>,
  DeleteRawReply extends RawReplyDefaultExpression<DeleteRawServer> = RawReplyDefaultExpression<DeleteRawServer>,
  DeleteTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  DeleteLogger extends FastifyBaseLogger = FastifyBaseLogger,
  DeleteRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  DeleteContextConfig = ContextConfigDefault,
  DeleteSchemaCompiler extends FastifySchema = FastifySchema,
  OptionsRawServer extends RawServerBase = RawServerDefault,
  OptionsRawRequest extends RawRequestDefaultExpression<OptionsRawServer> = RawRequestDefaultExpression<OptionsRawServer>,
  OptionsRawReply extends RawReplyDefaultExpression<OptionsRawServer> = RawReplyDefaultExpression<OptionsRawServer>,
  OptionsTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  OptionsLogger extends FastifyBaseLogger = FastifyBaseLogger,
  OptionsRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  OptionsContextConfig = ContextConfigDefault,
  OptionsSchemaCompiler extends FastifySchema = FastifySchema,
  PatchRawServer extends RawServerBase = RawServerDefault,
  PatchRawRequest extends RawRequestDefaultExpression<PatchRawServer> = RawRequestDefaultExpression<PatchRawServer>,
  PatchRawReply extends RawReplyDefaultExpression<PatchRawServer> = RawReplyDefaultExpression<PatchRawServer>,
  PatchTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  PatchLogger extends FastifyBaseLogger = FastifyBaseLogger,
  PatchRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  PatchContextConfig = ContextConfigDefault,
  PatchSchemaCompiler extends FastifySchema = FastifySchema,
  AllRawServer extends RawServerBase = RawServerDefault,
  AllRawRequest extends RawRequestDefaultExpression<AllRawServer> = RawRequestDefaultExpression<AllRawServer>,
  AllRawReply extends RawReplyDefaultExpression<AllRawServer> = RawReplyDefaultExpression<AllRawServer>,
  AllTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  AllLogger extends FastifyBaseLogger = FastifyBaseLogger,
  AllRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  AllContextConfig = ContextConfigDefault,
  AllSchemaCompiler extends FastifySchema = FastifySchema
> {
  get?: Route<GetRawServer, GetRawRequest, GetRawReply, GetTypeProvider, GetLogger, GetRouteGeneric, GetContextConfig, GetSchemaCompiler>;
  head?: Route<HeadRawServer, HeadRawRequest, HeadRawReply, HeadTypeProvider, HeadLogger, HeadRouteGeneric, HeadContextConfig, HeadSchemaCompiler>;
  post?: Route<PostRawServer, PostRawRequest, PostRawReply, PostTypeProvider, PostLogger, PostRouteGeneric, PostContextConfig, PostSchemaCompiler>;
  put?: Route<PutRawServer, PutRawRequest, PutRawReply, PutTypeProvider, PutLogger, PutRouteGeneric, PutContextConfig, PutSchemaCompiler> ;
  delete?: Route<DeleteRawServer, DeleteRawRequest, DeleteRawReply, DeleteTypeProvider, DeleteLogger, DeleteRouteGeneric, DeleteContextConfig, DeleteSchemaCompiler>;
  options?: Route<OptionsRawServer, OptionsRawRequest, OptionsRawReply, OptionsTypeProvider, OptionsLogger, OptionsRouteGeneric, OptionsContextConfig, OptionsSchemaCompiler>;
  patch?: Route<PatchRawServer, PatchRawRequest, PatchRawReply, PatchTypeProvider, PatchLogger, PatchRouteGeneric, PatchContextConfig, PatchSchemaCompiler>;
  all?: Route<AllRawServer, AllRawRequest, AllRawReply, AllTypeProvider, AllLogger, AllRouteGeneric, AllContextConfig, AllSchemaCompiler>;
}

export function routes<
  T,
  GetRawServer extends RawServerBase = RawServerDefault,
  GetRawRequest extends RawRequestDefaultExpression<GetRawServer> = RawRequestDefaultExpression<GetRawServer>,
  GetRawReply extends RawReplyDefaultExpression<GetRawServer> = RawReplyDefaultExpression<GetRawServer>,
  GetTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  GetLogger extends FastifyBaseLogger = FastifyBaseLogger,
  GetRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  GetContextConfig = ContextConfigDefault,
  GetSchemaCompiler extends FastifySchema = FastifySchema,
  HeadRawServer extends RawServerBase = RawServerDefault,
  HeadRawRequest extends RawRequestDefaultExpression<HeadRawServer> = RawRequestDefaultExpression<HeadRawServer>,
  HeadRawReply extends RawReplyDefaultExpression<HeadRawServer> = RawReplyDefaultExpression<HeadRawServer>,
  HeadTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  HeadLogger extends FastifyBaseLogger = FastifyBaseLogger,
  HeadRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  HeadContextConfig = ContextConfigDefault,
  HeadSchemaCompiler extends FastifySchema = FastifySchema,
  PostRawServer extends RawServerBase = RawServerDefault,
  PostRawRequest extends RawRequestDefaultExpression<PostRawServer> = RawRequestDefaultExpression<PostRawServer>,
  PostRawReply extends RawReplyDefaultExpression<PostRawServer> = RawReplyDefaultExpression<PostRawServer>,
  PostTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  PostLogger extends FastifyBaseLogger = FastifyBaseLogger,
  PostRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  PostContextConfig = ContextConfigDefault,
  PostSchemaCompiler extends FastifySchema = FastifySchema,
  PutRawServer extends RawServerBase = RawServerDefault,
  PutRawRequest extends RawRequestDefaultExpression<PutRawServer> = RawRequestDefaultExpression<PutRawServer>,
  PutRawReply extends RawReplyDefaultExpression<PutRawServer> = RawReplyDefaultExpression<PutRawServer>,
  PutTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  PutLogger extends FastifyBaseLogger = FastifyBaseLogger,
  PutRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  PutContextConfig = ContextConfigDefault,
  PutSchemaCompiler extends FastifySchema = FastifySchema,
  DeleteRawServer extends RawServerBase = RawServerDefault,
  DeleteRawRequest extends RawRequestDefaultExpression<DeleteRawServer> = RawRequestDefaultExpression<DeleteRawServer>,
  DeleteRawReply extends RawReplyDefaultExpression<DeleteRawServer> = RawReplyDefaultExpression<DeleteRawServer>,
  DeleteTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  DeleteLogger extends FastifyBaseLogger = FastifyBaseLogger,
  DeleteRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  DeleteContextConfig = ContextConfigDefault,
  DeleteSchemaCompiler extends FastifySchema = FastifySchema,
  OptionsRawServer extends RawServerBase = RawServerDefault,
  OptionsRawRequest extends RawRequestDefaultExpression<OptionsRawServer> = RawRequestDefaultExpression<OptionsRawServer>,
  OptionsRawReply extends RawReplyDefaultExpression<OptionsRawServer> = RawReplyDefaultExpression<OptionsRawServer>,
  OptionsTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  OptionsLogger extends FastifyBaseLogger = FastifyBaseLogger,
  OptionsRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  OptionsContextConfig = ContextConfigDefault,
  OptionsSchemaCompiler extends FastifySchema = FastifySchema,
  PatchRawServer extends RawServerBase = RawServerDefault,
  PatchRawRequest extends RawRequestDefaultExpression<PatchRawServer> = RawRequestDefaultExpression<PatchRawServer>,
  PatchRawReply extends RawReplyDefaultExpression<PatchRawServer> = RawReplyDefaultExpression<PatchRawServer>,
  PatchTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  PatchLogger extends FastifyBaseLogger = FastifyBaseLogger,
  PatchRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  PatchContextConfig = ContextConfigDefault,
  PatchSchemaCompiler extends FastifySchema = FastifySchema,
  AllRawServer extends RawServerBase = RawServerDefault,
  AllRawRequest extends RawRequestDefaultExpression<AllRawServer> = RawRequestDefaultExpression<AllRawServer>,
  AllRawReply extends RawReplyDefaultExpression<AllRawServer> = RawReplyDefaultExpression<AllRawServer>,
  AllTypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  AllLogger extends FastifyBaseLogger = FastifyBaseLogger,
  AllRouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  AllContextConfig = ContextConfigDefault,
  AllSchemaCompiler extends FastifySchema = FastifySchema
>(r: Routes<
  GetRawServer,
  GetRawRequest,
  GetRawReply,
  GetTypeProvider,
  GetLogger,
  GetRouteGeneric,
  GetContextConfig,
  GetSchemaCompiler,
  HeadRawServer,
  HeadRawRequest,
  HeadRawReply,
  HeadTypeProvider,
  HeadLogger,
  HeadRouteGeneric,
  HeadContextConfig,
  HeadSchemaCompiler,
  PostRawServer,
  PostRawRequest,
  PostRawReply,
  PostTypeProvider,
  PostLogger,
  PostRouteGeneric,
  PostContextConfig,
  PostSchemaCompiler,
  PutRawServer,
  PutRawRequest,
  PutRawReply,
  PutTypeProvider,
  PutLogger,
  PutRouteGeneric,
  PutContextConfig,
  PutSchemaCompiler,
  DeleteRawServer,
  DeleteRawRequest,
  DeleteRawReply,
  DeleteTypeProvider,
  DeleteLogger,
  DeleteRouteGeneric,
  DeleteContextConfig,
  DeleteSchemaCompiler,
  OptionsRawServer,
  OptionsRawRequest,
  OptionsRawReply,
  OptionsTypeProvider,
  OptionsLogger,
  OptionsRouteGeneric,
  OptionsContextConfig,
  OptionsSchemaCompiler,
  PatchRawServer,
  PatchRawRequest,
  PatchRawReply,
  PatchTypeProvider,
  PatchLogger,
  PatchRouteGeneric,
  PatchContextConfig,
  PatchSchemaCompiler,
  AllRawServer,
  AllRawRequest,
  AllRawReply,
  AllTypeProvider,
  AllLogger,
  AllRouteGeneric,
  AllContextConfig,
  AllSchemaCompiler
> & T): T {
  return r;
}
